# Generated by Django 2.2.5 on 2020-01-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_ticket_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customerName',
        ),
        migrations.AddField(
            model_name='ticket',
            name='brand',
            field=models.CharField(default='Jatin', max_length=20, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='customerFirstName',
            field=models.CharField(default='Nihar', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='customerLastName',
            field=models.CharField(default='sda', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.CharField(default='sdfsf', max_length=100, verbose_name='Product Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='serialNumber',
            field=models.CharField(default='sfdsaf', max_length=100, verbose_name='Serial Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phoneNumber',
            field=models.PositiveIntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receivedOn',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.PositiveIntegerField(unique=True, verbose_name='Ticket ID'),
        ),
    ]
