# Generated by Django 2.2.5 on 2020-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0004_auto_20200109_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='emailID',
            field=models.EmailField(default='jatinag1996@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
