# Generated by Django 2.2.5 on 2020-01-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0005_ticket_emailid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCenters',
            new_name='ServiceCenter',
        ),
    ]
