# Generated by Django 2.2.5 on 2020-01-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
